development:
  database: terminology_development
  adapter: postgresql
  encoding: unicode
  username: ang
  password: ehr
  host: localhost

test:
  database: terminology_test
  adapter: postgresql
  encoding: unicode
  username: ang
  password: ehr
  host: localhost

production: 
  database: terminology_production
  adapter: postgresql
  encoding: unicode
  username: ang
  password: ehr
