require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CodesetsController do

  # This should return the minimal set of attributes required to create a valid
  # Codeset. As you add validations to Codeset, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CodesetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all codesets as @codesets" do
      codeset = Codeset.create! valid_attributes
      get :index, {}, valid_session
      assigns(:codesets).should eq([codeset])
    end
  end

  describe "GET show" do
    it "assigns the requested codeset as @codeset" do
      codeset = Codeset.create! valid_attributes
      get :show, {:id => codeset.to_param}, valid_session
      assigns(:codeset).should eq(codeset)
    end
  end

  describe "GET new" do
    it "assigns a new codeset as @codeset" do
      get :new, {}, valid_session
      assigns(:codeset).should be_a_new(Codeset)
    end
  end

  describe "GET edit" do
    it "assigns the requested codeset as @codeset" do
      codeset = Codeset.create! valid_attributes
      get :edit, {:id => codeset.to_param}, valid_session
      assigns(:codeset).should eq(codeset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Codeset" do
        expect {
          post :create, {:codeset => valid_attributes}, valid_session
        }.to change(Codeset, :count).by(1)
      end

      it "assigns a newly created codeset as @codeset" do
        post :create, {:codeset => valid_attributes}, valid_session
        assigns(:codeset).should be_a(Codeset)
        assigns(:codeset).should be_persisted
      end

      it "redirects to the created codeset" do
        post :create, {:codeset => valid_attributes}, valid_session
        response.should redirect_to(Codeset.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved codeset as @codeset" do
        # Trigger the behavior that occurs when invalid params are submitted
        Codeset.any_instance.stub(:save).and_return(false)
        post :create, {:codeset => {}}, valid_session
        assigns(:codeset).should be_a_new(Codeset)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Codeset.any_instance.stub(:save).and_return(false)
        post :create, {:codeset => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested codeset" do
        codeset = Codeset.create! valid_attributes
        # Assuming there are no other codesets in the database, this
        # specifies that the Codeset created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Codeset.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => codeset.to_param, :codeset => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested codeset as @codeset" do
        codeset = Codeset.create! valid_attributes
        put :update, {:id => codeset.to_param, :codeset => valid_attributes}, valid_session
        assigns(:codeset).should eq(codeset)
      end

      it "redirects to the codeset" do
        codeset = Codeset.create! valid_attributes
        put :update, {:id => codeset.to_param, :codeset => valid_attributes}, valid_session
        response.should redirect_to(codeset)
      end
    end

    describe "with invalid params" do
      it "assigns the codeset as @codeset" do
        codeset = Codeset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Codeset.any_instance.stub(:save).and_return(false)
        put :update, {:id => codeset.to_param, :codeset => {}}, valid_session
        assigns(:codeset).should eq(codeset)
      end

      it "re-renders the 'edit' template" do
        codeset = Codeset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Codeset.any_instance.stub(:save).and_return(false)
        put :update, {:id => codeset.to_param, :codeset => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested codeset" do
      codeset = Codeset.create! valid_attributes
      expect {
        delete :destroy, {:id => codeset.to_param}, valid_session
      }.to change(Codeset, :count).by(-1)
    end

    it "redirects to the codesets list" do
      codeset = Codeset.create! valid_attributes
      delete :destroy, {:id => codeset.to_param}, valid_session
      response.should redirect_to(codesets_url)
    end
  end

end
